version: '3.8'

services:
  nodejs-app-1:
    image: dailydonuts/first-web-app:latest
    container_name: first-web-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nodejs-app-2:
    image: dailydonuts/second-web-app:latest
    container_name: second-web-app
    ports:
      - "4000:4000"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - app-network
    depends_on:
      - nodejs-app-1
      - nodejs-app-2
      - alertmanager
      - node-exporter  # Ensures Prometheus starts after node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    volumes:
      - grafana-data:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network

  puppeteer:
    image: dailydonuts/puppeteer:latest
    container_name: puppeteer
    networks:
      - app-network
    depends_on:
      - nodejs-app-1
      - nodejs-app-2
    environment:
      - PUPPETEER_HEADLESS=true
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  grafana-data:
