global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['first-web-app:3000']

  - job_name: 'nodejs-app-2'
    static_configs:
      - targets: ['second-web-app:4000']