global:
  scrape_interval: 10s  # How often to scrape targets
  evaluation_interval: 15s  # How often to evaluate rules

rule_files:
  - "/etc/prometheus/alert.rules.yml"  # Make sure this file exists

scrape_configs:
  # Monitor first Node.js app
  - job_name: "nodejs-app"
    static_configs:
      - targets: ["first-web-app:3000"]

  # Monitor second Node.js app
  - job_name: "nodejs-app-2"
    static_configs:
      - targets: ["second-web-app:4000"]

  # Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Monitor system metrics using Node Exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
